language: bash

sudo: false

services:
  - docker

before_script:
  - make image no-cache=yes tag=test
  - make deps.bats
  - docker pull hairyhenderson/gomplate:slim

script:
  - make test tag=test

notifications:
  email:
    on_success: never
    on_failure: always
